genome:
    models:
      - lightblue/suzume-llama-3-8B-japanese
      - rinna/llama-3-youko-8b
    merge_method: dare_ties
    base_model: meta-llama/Meta-Llama-3-8B-Instruct
    tokenizer_source: null
    layer_granularity: 8 # sane default
    allow_negative_weights: true # useful with task_arithmetic
    smooth: true
    filters:
      - self_attn
      - mlp
    
tasks:
  - name: elyzatasks100 #- name: elyzatasks100
    weight: 1.0 #weight: 0.0
